# Generated by Django 4.2.27 on 2026-02-24 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_enrollment_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enrollment',
            name='progress',
        ),
    ]
