# Generated by Django 4.2.27 on 2026-02-24 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_enrollment_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='level',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('pro', 'Pro Developer')], default='beginner', max_length=20),
        ),
    ]
