# Generated by Django 4.2.27 on 2026-02-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_registration_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
