# Generated by Django 4.2.27 on 2026-03-03 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_course_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
