# Generated by Django 4.2.27 on 2026-03-10 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_course_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('razorpay_payment_id', models.CharField(max_length=200)),
                ('razorpay_order_id', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registration')),
            ],
        ),
    ]
