# Generated by Django 6.0.3 on 2026-03-23 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0009_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='completions', to='app1.lessons')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app1.registration')),
            ],
            options={
                'unique_together': {('user', 'lesson')},
            },
        ),
    ]
