# Generated by Django 6.0.3 on 2026-03-30 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app1", "0010_lessoncompletion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quiz",
            name="course",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="quizzes",
                to="app1.course",
            ),
        ),
    ]
